version: 2
allowlists:
  - description: "Allow ImageKit public key"
    secrets:
      - "public_ufGz5cbxtezdf9UH+tgW+M7+Vc0="
  - description: "Allow ImageKit private key"
    secrets:
      - "private_6ShspqgqatVYjdaQdM/ve/pUQPE="
